inherit_gem:
  rubocop_defaults: .rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/StderrPuts:
  Enabled: false
