---
os: linux
language: ruby
cache: bundler

jobs:
  include:
    - stage: lint
      rvm: 2.6.5
      osx_image: xcode11.3
      addons:
        homebrew:
          packages:
          - shellcheck
      before_install: gem install bundler -v 2.0.2
      script:
      - bundle exec rubocop
      - shellcheck lib/**/*.sh

    - &test_stage
      stage: test
      rvm: 2.7.0
      before_install: gem install bundler -v 2.0.2
    - <<: *test_stage
      rvm: 2.6.5
    - <<: *test_stage
      rvm: 2.5.7
    - <<: *test_stage
      rvm: 2.4.9
    - <<: *test_stage
      rvm: 2.3.8
    - <<: *test_stage
      rvm: 2.2.10
      before_install: skip

    - &install_stage
      language: bash
      stage: install
      os: osx
      osx_image: xcode11.3 # macOS 10.14 Mojave
      script:
        - ruby -v
        - ./start.sh
    - <<: *install_stage
      osx_image: xcode9.4 # macOS 10.13 High Sierra
    - <<: *install_stage
      osx_image: xcode9.2 # macOS 10.12 Sierra
    - <<: *install_stage
      osx_image: xcode8 # macOS 10.11 El Capitan
    - <<: *install_stage
      osx_image: xcode6.4 # macOS 10.10 Yosemite

stages:
  - lint
  - test
  - install
