# required tools
dependencies:
  - brew
  - ruby:
      dependencies:
        manager:
          - rbenv
          - rvm
          - chruby
          - asdf

# Sorceress steps (always run regardless of any user steps)
prerequisites:
  - core/find_dependencies
  - core/install_features

# User steps
steps: []
